# Generated by Django 5.0.6 on 2024-05-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=400)),
                ('monthly_income', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('approval', models.CharField(max_length=100)),
                ('disbursed', models.BooleanField(default=False)),
                ('lender', models.CharField(max_length=100)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.borrowerprofile')),
            ],
        ),
    ]
