# Generated by Django 5.0.3 on 2024-05-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.PositiveIntegerField()),
                ('amount', models.CharField(max_length=100)),
                ('period', models.PositiveIntegerField()),
                ('approval', models.CharField(max_length=100)),
                ('lender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=400)),
                ('monthly_income', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('mobile',)},
            },
        ),
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.PositiveIntegerField()),
                ('otp', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('mobile',)},
            },
        ),
    ]
